include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    avoid_print: ignore
    public_member_api_docs: ignore
  language:
    strict-inference: false

  exclude:
    - /**/*.g.dart
