name: typesafe_supabase_example

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  supabase: ^2.1.3
  typesafe_supabase:
    path: ../

dev_dependencies:
  build_runner: ^2.4.11
  very_good_analysis: ^6.0.0
