CREATE TABLE "public"."books"(
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "title" text NOT NULL,
    "author" text NOT NULL,
    "pages" smallint
);

CREATE UNIQUE INDEX books_pkey ON public.books USING btree(id);

ALTER TABLE "public"."books"
    ADD CONSTRAINT "books_pkey" PRIMARY KEY USING INDEX "books_pkey";

GRANT DELETE ON TABLE "public"."books" TO "anon";

GRANT INSERT ON TABLE "public"."books" TO "anon";

GRANT REFERENCES ON TABLE "public"."books" TO "anon";

GRANT SELECT ON TABLE "public"."books" TO "anon";

GRANT TRIGGER ON TABLE "public"."books" TO "anon";

GRANT TRUNCATE ON TABLE "public"."books" TO "anon";

GRANT UPDATE ON TABLE "public"."books" TO "anon";

GRANT DELETE ON TABLE "public"."books" TO "authenticated";

GRANT INSERT ON TABLE "public"."books" TO "authenticated";

GRANT REFERENCES ON TABLE "public"."books" TO "authenticated";

GRANT SELECT ON TABLE "public"."books" TO "authenticated";

GRANT TRIGGER ON TABLE "public"."books" TO "authenticated";

GRANT TRUNCATE ON TABLE "public"."books" TO "authenticated";

GRANT UPDATE ON TABLE "public"."books" TO "authenticated";

GRANT DELETE ON TABLE "public"."books" TO "service_role";

GRANT INSERT ON TABLE "public"."books" TO "service_role";

GRANT REFERENCES ON TABLE "public"."books" TO "service_role";

GRANT SELECT ON TABLE "public"."books" TO "service_role";

GRANT TRIGGER ON TABLE "public"."books" TO "service_role";

GRANT TRUNCATE ON TABLE "public"."books" TO "service_role";

GRANT UPDATE ON TABLE "public"."books" TO "service_role";

