builders:
  supa_table:
    import: "package:typesafe_supabase/builder.dart"
    builder_factories: ["supaTableBuilder"]
    build_extensions: { ".dart": [".supa_table.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]
