name: typesafe_supabase
description: A dart package that enables type-safe queries to a Supabase database.
version: 0.0.1
repository: https://github.com/JakesMD/typesafe-supabase

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  meta: ^1.17.0
  supabase: ^2.8.0
  typesafe_postgrest: ^0.0.1

dev_dependencies:
  very_good_analysis: ^9.0.0
