name: typesafe_supabase
description: A dart package that enables type-safe queries to a Supabase database.
version: 0.0.3
repository: https://github.com/JakesMD/typesafe-supabase

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  meta: ^1.16.0
  supabase: ^2.8.0
  typesafe_postgrest: ^0.1.0

dev_dependencies:
  very_good_analysis: ^9.0.0
