name: typesafe_supabase
description: A dart package that enables type-safe queries to a Supabase database.
version: 0.0.1-dev.3
repository: https://github.com/JakesMD/typesafe-supabase

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  analyzer: ^6.5.0
  build: ^2.4.1
  meta: ^1.12.0
  source_gen: ^1.5.0
  supabase: ^2.1.3

dev_dependencies:
  very_good_analysis: ^6.0.0
